### ISSUE TITLE
Swarm multiple dat's together

### ISSUE THREAD

**Issue by joehand** [datproject/dat-node#201]
Dat server tools like: https://github.com/beakerbrowser/homebase and https://github.com/new-computers/seeder are a great use case for managing multiple dat-node instances in a single swarm. I imagine we could have an API like:

```js
var swarm = Dat.createSwarm([opts])
Dat('/dir', function (err, dat) {
  var network = dat.joinNetwork(swarm)
  
  network.on('connection', () => {
     // TODO: how would we handle something like this?
     // want to make it easy to track only network things on this dat.
  })
})
```

**Comment by pfrazee** [comment]
That API design seems right. For the connection events, there's [some code you can steal from beaker](https://github.com/beakerbrowser/beaker/blob/master/app/background-process/networks/dat/logging-utils.js).

Most/all of the events needed have a `peer` object with the `.channel` attribute, which should be the dkey. I don't recall if that will give you coverage of feeds being synced in addition to the main feed of the connection, but it will at least give you the main one. If not, we can listen to `stream.on('feed')` and attach the additional feeds to the events.

You also have to deal with the truncated dkeys, but that'll be a temporary kludge since we're moving away from the bittorrent dht.

**Comment by karissa** [comment]
Seems to me like you might reverse the join swarm call, so that the swarm is the first class object. Otherwise you could have a couple swarm objects hanging around and it's unclear which swarm is which (or is it the same swarm?)

```js
var swarm = Dat.createSwarm([opts])
Dat('/dir', function (err, dat) {
   swarm.join(dat)
})
```

So it would take extending the `swarm.join` function to accept also a dat object

**Comment by okdistribute** [comment]
hyperswarm does this automatically with the `multiplex: true` option
