### ISSUE TITLE
Feature Request: Promise API

### ISSUE THREAD

**Issue by martinheidegger** [datproject/dat-node#221]
Many other projects in the Node eco-system have changed to an optional Promise API, I would love to have it in DAT as well.

**Comment by RangerMauve** [comment]
You might be interested in using [node-dat-archive](https://github.com/beakerbrowser/node-dat-archive) or [@beaker/dat-node](https://github.com/beakerbrowser/dat-node) since they use the same promise-based APIs as Beaker.

This gives you the benefit of any code you write also working in Beaker.

Also, since I'm shameless, you could try targeting [webrun](https://github.com/RangerMauve/webrun) which provides browser APIs (including the DatArchive API from beaker) and can be used in conjunction with node modules. This way you can write code that works in Beaker or the web first, and then sprinkle in any Node.js stuff you'd want.

**Comment by martinheidegger** [comment]
I know that `node-dat-archive` and `@beaker/dat-node` exist, but I wonder why they are separate from `dat-node`. From a system-architecture perspective I can understand that you shouldn't pack too-much features into one project, but it seems to me that this super-thin approach seems to only discourage people to actually use DAT _(particularly pointing out the missing promises)_. After all: Beaker didn't add those features for fun, but because they knew that a wider audience relies on promises to work.

**Comment by okdistribute** [comment]
Use dat-sdk for a promise API! It works! 

This dat-node library doesn't have any full-time maintainers so I'd recommend keeping efforts here minimal, only for major improvements/features or critical bug and vulnerability fixes. Thanks!
